language: go

go:
    - "1.11.x"
    - tip

install:
    # Get all imported packages
    - make install-deps install-deps-dev

    # Basic build errors
    - make build

script:
    # Lint
    - make format-lint
    - make import-lint
    - make style-lint

    # Run tests
    - make test-with-coverage

matrix:
    allow_failures:
        - go: tip
    fast_finish: true
